// Block registry. Each block: id, name, color (for texture), solidity, etc.
export const B = {
  AIR: 0, GRASS: 1, DIRT: 2, STONE: 3, SAND: 4, WOOD: 5, LEAVES: 6,
  PLANKS: 7, BEAM: 8, WALL_STONE: 9, WALL_WOOD: 10, FIREPLACE: 11,
  IRON_ORE: 12, GOLD_ORE: 13, DIAMOND_ORE: 14, PLATINUM_ORE: 15,
  COBBLE: 16, GLASS: 17, BRICK: 18, ARCH: 19, TORCH: 20,
  IRON_BLOCK: 21, GOLD_BLOCK: 22, DIAMOND_BLOCK: 23, PLATINUM_BLOCK: 24,
  BEDROCK: 25, WATER: 26,
  RAW_BEEF: 27, COOKED_BEEF: 28,
  PICKAXE_WOOD: 29, PICKAXE_IRON: 30, PICKAXE_DIAMOND: 31, PICKAXE_PLATINUM: 32,
  PICKAXE_STONE: 33,
  SEAGRASS: 34, RAW_FISH: 35, COOKED_FISH: 36,
  CHEST: 37,
  DOOR: 38, DOOR_TOP: 39,
  TRADER: 40,
  TWIG: 41,
  ICE: 42,
  CACTUS: 43,
  SNOW: 44,
  LAVA: 45,
  KELP: 46,
  CORAL: 47,
  PORTAL: 48,
  BUCKET: 49,
  WATER_BUCKET: 50,
  LAVA_BUCKET: 51,
  MOON_ROCK: 52,
  MOON_DUST: 53,
  MOON_STONE: 54,
  PLATINUM_TROPHY: 55,
  WIRE: 56,
  LEVER: 57,
  LAMP: 58,
  GRANITE: 59,
  MARBLE: 60,
  BASALT: 61,
  SHOVEL_WOOD: 62,
  SHOVEL_STONE: 63,
  SHOVEL_IRON: 64,
  SHOVEL_DIAMOND: 65,
  SHOVEL_PLATINUM: 66,
  CRYSTAL: 67,
  GLOW_MUSHROOM: 68,
  PISTON: 69,
  STICKY_PISTON: 70,
  PISTON_HEAD: 71,
  ROTTEN_FLESH: 72,
  BONE: 73,
};

export const BLOCKS = {
  [B.AIR]:    { name: "air",     solid: false, transparent: true },
  [B.GRASS]:  { name: "grass",   solid: true,  hardness: 0.6, top: "#5fa83a", side: "#8a6a3a", bottom: "#6a4a2a" },
  [B.DIRT]:   { name: "dirt",    solid: true,  hardness: 0.6, color: "#6a4a2a" },
  [B.STONE]:  { name: "stone",   solid: true,  hardness: 1.5, color: "#888888", toolTier: 1 },
  [B.SAND]:   { name: "sand",    solid: true,  hardness: 0.5, color: "#e3d9a2" },
  [B.WOOD]:   { name: "wood",    solid: true,  hardness: 1.2, top: "#a07a3a", side: "#6b4a1f" },
  [B.LEAVES]: { name: "leaves",  solid: true,  hardness: 0.3, color: "#3a7a2a", transparent: true },
  [B.PLANKS]: { name: "planks",  solid: true,  hardness: 1.0, color: "#c89656" },
  [B.BEAM]:   { name: "beam",    solid: true,  hardness: 1.0, color: "#8a5f28" },
  [B.WALL_STONE]: { name: "wall_stone", solid: true, hardness: 3.0, color: "#6e6e72" },
  [B.WALL_WOOD]:  { name: "wall_wood",  solid: true, hardness: 2.0, color: "#7a5a2a" },
  [B.FIREPLACE]: { name: "fireplace", solid: true, hardness: 3.5, color: "#3a2a1a", light: 14 },
  [B.IRON_ORE]: { name: "iron_ore", solid: true, hardness: 2.5, color: "#7a6a55", toolTier: 2 },
  [B.GOLD_ORE]: { name: "gold_ore", solid: true, hardness: 3.0, color: "#807038", toolTier: 2 },
  [B.DIAMOND_ORE]: { name: "diamond_ore", solid: true, hardness: 4.0, color: "#5a6868", toolTier: 3 },
  [B.PLATINUM_ORE]: { name: "platinum_ore", solid: true, hardness: 5.0, color: "#a8acb0", toolTier: 4 },
  [B.PICKAXE_STONE]: { name: "pickaxe_stone", solid: false, hardness: 0.1, color: "#9a9a9a", item: true, tool: "pickaxe", toolTier: 2 },
  [B.SEAGRASS]: { name: "seagrass", solid: false, hardness: 0.1, color: "#2a7a3a", transparent: true, decor: true },
  [B.RAW_FISH]: { name: "raw_fish", solid: false, hardness: 0.1, color: "#c8d8e0", item: true, food: 2 },
  [B.COOKED_FISH]: { name: "cooked_fish", solid: false, hardness: 0.1, color: "#e8c890", item: true, food: 7 },
  [B.CHEST]: { name: "chest", solid: true, hardness: 1.0, color: "#8a5a2a", interactive: true },
  [B.DOOR]: { name: "door", solid: true, hardness: 1.0, color: "#a07a3a", interactive: true, transparent: true, door: true },
  [B.DOOR_TOP]: { name: "door_top", solid: false, hardness: 1.0, color: "#a07a3a", transparent: true, decor: true, door: true },
  [B.TRADER]: { name: "trader", solid: true, hardness: 2.0, color: "#5a3a1a", interactive: true, trader: true },
  [B.COBBLE]: { name: "cobble", solid: true, hardness: 1.8, color: "#7c7c80", toolTier: 1 },
  [B.WALL_STONE]: { name: "wall_stone", solid: true, hardness: 3.0, color: "#6e6e72", toolTier: 1 },
  [B.BRICK]: { name: "brick", solid: true, hardness: 2.5, color: "#a23a2a", toolTier: 1 },
  [B.GLASS]:  { name: "glass", solid: true, hardness: 0.4, color: "#bcd8e8", transparent: true },
  [B.BRICK]:  { name: "brick", solid: true, hardness: 2.5, color: "#a23a2a" },
  [B.ARCH]:   { name: "arch", solid: false, hardness: 1.2, color: "#c89656", transparent: true, decor: true },
  [B.TORCH]:  { name: "torch", solid: false, hardness: 0.2, color: "#ffaa33", transparent: true, light: 12 },
  [B.IRON_BLOCK]: { name: "iron_block", solid: true, hardness: 3.5, color: "#dcdcdc" },
  [B.GOLD_BLOCK]: { name: "gold_block", solid: true, hardness: 3.5, color: "#ffe040" },
  [B.DIAMOND_BLOCK]: { name: "diamond_block", solid: true, hardness: 4.5, color: "#8af6ff" },
  [B.PLATINUM_BLOCK]: { name: "platinum_block", solid: true, hardness: 5.0, color: "#f0f0f8" },
  [B.BEDROCK]: { name: "bedrock", solid: true, hardness: Infinity, color: "#1a1a1a" },
  [B.WATER]:  { name: "water", solid: false, hardness: Infinity, color: "#3a6acc", transparent: true, liquid: true },
  [B.RAW_BEEF]: { name: "raw_beef", solid: false, hardness: 0.1, color: "#c66a72", item: true, food: 2 },
  [B.COOKED_BEEF]: { name: "cooked_beef", solid: false, hardness: 0.1, color: "#8a4a2a", item: true, food: 7 },
  [B.PICKAXE_WOOD]: { name: "pickaxe_wood", solid: false, hardness: 0.1, color: "#a07a3a", item: true, tool: "pickaxe", toolTier: 1 },
  [B.PICKAXE_IRON]: { name: "pickaxe_iron", solid: false, hardness: 0.1, color: "#dcdcdc", item: true, tool: "pickaxe", toolTier: 3 },
  [B.PICKAXE_DIAMOND]: { name: "pickaxe_diamond", solid: false, hardness: 0.1, color: "#8af6ff", item: true, tool: "pickaxe", toolTier: 4 },
  [B.PICKAXE_PLATINUM]: { name: "pickaxe_platinum", solid: false, hardness: 0.1, color: "#f0f0f8", item: true, tool: "pickaxe", toolTier: 5 },
  [B.TWIG]: { name: "twig", solid: false, hardness: 0.1, color: "#8a5f28", item: true },
  [B.ICE]:   { name: "ice",   solid: true,  hardness: 0.6, color: "#9cc4d8", transparent: true },
  [B.CACTUS]:{ name: "cactus",solid: true,  hardness: 0.4, color: "#3a7a3a" },
  [B.SNOW]:  { name: "snow",  solid: true,  hardness: 0.3, color: "#eef2f6" },
  [B.LAVA]:  { name: "lava", solid: false, hardness: Infinity, color: "#e04020", transparent: true, liquid: true, light: 15, damage: 4 },
  [B.KELP]:  { name: "kelp", solid: false, hardness: 0.1, color: "#2a4a1a", transparent: true, decor: true },
  [B.CORAL]: { name: "coral", solid: false, hardness: 0.2, color: "#ff7a8a", transparent: true, decor: true },
  [B.PORTAL]: { name: "portal", solid: false, hardness: Infinity, color: "#a070ff", transparent: true, liquid: false, light: 11, portal: true },
  [B.BUCKET]:       { name: "bucket",       solid: false, hardness: 0.1, color: "#a0a0a0", item: true, bucket: true, empty: true },
  [B.WATER_BUCKET]: { name: "water_bucket", solid: false, hardness: 0.1, color: "#3a6acc", item: true, bucket: true, contains: "WATER" },
  [B.LAVA_BUCKET]:  { name: "lava_bucket",  solid: false, hardness: 0.1, color: "#e04020", item: true, bucket: true, contains: "LAVA" },
  [B.MOON_ROCK]:   { name: "moon_rock",   solid: true, hardness: 2.5, color: "#7a7a82", toolTier: 1 },
  [B.MOON_DUST]:   { name: "moon_dust",   solid: true, hardness: 0.4, color: "#b0b0b8" },
  [B.MOON_STONE]:  { name: "moon_stone",  solid: true, hardness: 3.0, color: "#5a5a62", toolTier: 2 },
  [B.PLATINUM_TROPHY]: { name: "platinum_trophy", solid: true, hardness: 1.5, color: "#f0f0f8", light: 12, decor: true, trophy: true },
  [B.WIRE]:  { name: "wire",  solid: false, hardness: 0.1, color: "#cc1010", transparent: true, decor: true, wire: true },
  [B.LEVER]: { name: "lever", solid: false, hardness: 0.3, color: "#7a5a3a", transparent: true, decor: true, interactive: true, lever: true, source: true },
  [B.LAMP]:  { name: "lamp",  solid: true,  hardness: 0.6, color: "#888888", transparent: false, lamp: true, receiver: true },
  [B.GRANITE]: { name: "granite", solid: true, hardness: 1.7, color: "#9a5a4a", toolTier: 1 },
  [B.MARBLE]:  { name: "marble",  solid: true, hardness: 1.5, color: "#e8e4d8" },
  [B.BASALT]:  { name: "basalt",  solid: true, hardness: 2.2, color: "#2a2a32", toolTier: 1 },
  [B.SHOVEL_WOOD]:     { name: "shovel_wood",     solid: false, hardness: 0.1, color: "#a07a3a", item: true, tool: "shovel", toolTier: 1 },
  [B.SHOVEL_STONE]:    { name: "shovel_stone",    solid: false, hardness: 0.1, color: "#9a9a9a", item: true, tool: "shovel", toolTier: 2 },
  [B.SHOVEL_IRON]:     { name: "shovel_iron",     solid: false, hardness: 0.1, color: "#dcdcdc", item: true, tool: "shovel", toolTier: 3 },
  [B.SHOVEL_DIAMOND]:  { name: "shovel_diamond",  solid: false, hardness: 0.1, color: "#8af6ff", item: true, tool: "shovel", toolTier: 4 },
  [B.SHOVEL_PLATINUM]: { name: "shovel_platinum", solid: false, hardness: 0.1, color: "#f0f0f8", item: true, tool: "shovel", toolTier: 5 },
  [B.CRYSTAL]: { name: "crystal", solid: false, hardness: 0.4, color: "#5affe0", transparent: true, decor: true, light: 9 },
  [B.GLOW_MUSHROOM]: { name: "glow_mushroom", solid: false, hardness: 0.1, color: "#a0e0ff", transparent: true, decor: true, light: 8 },
  [B.PISTON]: { name: "piston", solid: true, hardness: 1.5, color: "#9c7a4a", interactive: true, piston: true, receiver: true },
  [B.STICKY_PISTON]: { name: "sticky_piston", solid: true, hardness: 1.5, color: "#4e8050", interactive: true, piston: true, sticky: true, receiver: true },
  [B.PISTON_HEAD]: { name: "piston_head", solid: false, hardness: 0.5, color: "#c8b070", transparent: true, decor: true, pistonHead: true },
  [B.ROTTEN_FLESH]: { name: "rotten_flesh", solid: false, hardness: 0.1, color: "#7a4a4a", item: true, food: 1 },
  [B.BONE]: { name: "bone", solid: false, hardness: 0.1, color: "#e8e0c8", item: true },
};

export const isSolid = (id) => id !== B.AIR && !!BLOCKS[id]?.solid;
export const isTransparent = (id) => id === B.AIR || !!BLOCKS[id]?.transparent;
export const isLiquid = (id) => !!BLOCKS[id]?.liquid;
export const isDecor = (id) => !!BLOCKS[id]?.decor;
